#include <File.au3>

Opt("WinTitleMatchMode", 2)
Opt("WinSearchChildren", 1)

$const = "ver. 095"

Global $un
Global $mas
Global $rff
Global $fString
Global $file

Func fill_w()
   If WinWait("Ёлектронна€ почта »нтернета","",60) = 0 Then Exit(0)
   WinSetState("Ёлектронна€ почта »нтернета","",@SW_HIDE)
   ControlSend("Ёлектронна€ почта »нтернета","","[CLASS:RichEdit20WPT; INSTANCE:2]",$rff[3])
   ControlClick("Ёлектронна€ почта »нтернета","","[CLASS:Button; INSTANCE:1]","left")
   ControlClick("Ёлектронна€ почта »нтернета","","[CLASS:Button; INSTANCE:2]","left")
EndFunc

Func when_found()
   FileClose($file)
   If $rff[2] = "" Then  MsgBox(16,"!!!!","Ќе найдена учетна€ запись почты")
   $un = $rff[2]
   prf_gen()
   ShellExecute("outlook.exe","/importprf c:\temp\out.prf")
   fill_w()
   Exit(0)
EndFunc

$cl = _FileCountLines("\\172.16.166.5\maildb\users.dbm")
Local $file = FileOpen("\\172.16.166.5\maildb\users.dbm", 0)

For $i = 1 To $cl
   $fString = FileReadLine($file,$i)
   If @error = -1 Then ExitLoop
   $rff = StringSplit($fstring,";")
   If $rff[1] = @UserName Then when_found()
Next

Func prf_gen()
   Local $file2 = FileOpen("c:\temp\out.prf", 2)
   FileWrite($file2,";Automatically generated PRF file from the Microsoft Office Customization and Installation Wizard" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"; **************************************************************" & @CRLF)
   FileWrite($file2,"; Section 1 - Profile Defaults" & @CRLF)
   FileWrite($file2,"; **************************************************************" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[General]" & @CRLF)
   FileWrite($file2,"Custom=1" & @CRLF)
   FileWrite($file2,"ProfileName="&$un & @CRLF)
   FileWrite($file2,"DefaultProfile=Yes" & @CRLF)
   FileWrite($file2,"OverwriteProfile=Append" & @CRLF)
   FileWrite($file2,"ModifyDefaultProfileIfPresent=false" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"; **************************************************************" & @CRLF)
   FileWrite($file2,"; Section 2 - Services in Profile" & @CRLF)
   FileWrite($file2,"; **************************************************************" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Service List]" & @CRLF)
   FileWrite($file2,";ServiceX=Microsoft Outlook Client" & @CRLF)
   FileWrite($file2,";Service1=LDAP Directory" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2,"; Section 3 - List of internet accounts" & @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Internet Account List]" & @CRLF)
   FileWrite($file2,"Account1=I_Mail" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2,"; Section 4 - Default values for each service." & @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,";[ServiceX]" & @CRLF)
   FileWrite($file2,";FormDirectoryPage=" & @CRLF)
   FileWrite($file2,";-- The URL of Exchange Web Services Form Directory page used to create Web forms." & @CRLF)
   FileWrite($file2,";WebServicesLocation=" & @CRLF)
   FileWrite($file2,";-- The URL of Exchange Web Services page used to display unknown forms." & @CRLF)
   FileWrite($file2,";ComposeWithWebServices=" & @CRLF)
   FileWrite($file2,";-- Set to true to use Exchange Web Services to compose forms." & @CRLF)
   FileWrite($file2,";PromptWhenUsingWebServices=" & @CRLF)
   FileWrite($file2,";-- Set to true to use Exchange Web Services to display unknown forms." & @CRLF)
   FileWrite($file2,";OpenWithWebServices=" & @CRLF)
   FileWrite($file2,";-- Set to true to prompt user before opening unknown forms when using Exchange Web Services." & @CRLF)
   FileWrite($file2, @CRLF)
   FileWrite($file2, @CRLF)
   FileWrite($file2, "[Service1]" & @CRLF)
   FileWrite($file2, "UniqueService=No" & @CRLF)
   FileWrite($file2, "ServerName=nnkk-dc" & @CRLF)
   FileWrite($file2, "DisplayName=nn" & @CRLF)
   FileWrite($file2, "ConnectionPort=389" & @CRLF)
   FileWrite($file2, "UseSSL=false" & @CRLF)
   FileWrite($file2, "UseSPA=false" & @CRLF)
   FileWrite($file2, "EnableBrowsing=true" & @CRLF)
   FileWrite($file2, "UserName=" & $un & @CRLF)
   FileWrite($file2, "SearchBase=" & @CRLF)
   FileWrite($file2, "DefaultSearch=1" & @CRLF)
   FileWrite($file2, "SearchTimeout=60" & @CRLF)
   FileWrite($file2, "MaxEntriesReturned=100" & @CRLF)
   FileWrite($file2, "CheckNames=" & @CRLF)
   FileWrite($file2, @CRLF)
   FileWrite($file2, @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2,"; Section 5 - Values for each internet account." & @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Account1]" & @CRLF)
   FileWrite($file2,"UniqueService=No" & @CRLF)
   FileWrite($file2,"AccountName="& $un & @CRLF)
   FileWrite($file2,"POP3Server=pop.budzdorov.ru" & @CRLF)
   FileWrite($file2,"SMTPServer=smtp.budzdorov.ru" & @CRLF)
   FileWrite($file2,"POP3UserName="& $un & @CRLF)
   FileWrite($file2,"EmailAddress="&$un &"@nnkk.budzdorov.su" & @CRLF)
   FileWrite($file2,"POP3UseSPA=1" & @CRLF)
   FileWrite($file2,"DisplayName=%username%" & @CRLF)
   FileWrite($file2,"ReplyEMailAddress=" & @CRLF)
   FileWrite($file2,"SMTPUseAuth=1" & @CRLF)
   FileWrite($file2,"SMTPAuthMethod=0" & @CRLF)
   FileWrite($file2,"ConnectionType=0" & @CRLF)
   FileWrite($file2,"LeaveOnServer=0x90003" & @CRLF)
   FileWrite($file2,"POP3UseSSL=0" & @CRLF)
   FileWrite($file2,"ConnectionOID=MyConnection" & @CRLF)
   FileWrite($file2,"POP3Port=110" & @CRLF)
   FileWrite($file2,"ServerTimeOut=60" & @CRLF)
   FileWrite($file2,"SMTPPort=25" & @CRLF)
   FileWrite($file2,"SMTPSecureConnection=0" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2,"; Section 6 - Mapping for profile properties" & @CRLF)
   FileWrite($file2,";***************************************************************" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Microsoft Exchange Server]" & @CRLF)
   FileWrite($file2,"ServiceName=MSEMS" & @CRLF)
   FileWrite($file2,"MDBGUID=5494A1C0297F101BA58708002B2A2517" & @CRLF)
   FileWrite($file2,"MailboxName=PT_STRING8,0x6607" & @CRLF)
   FileWrite($file2,"HomeServer=PT_STRING8,0x6608" & @CRLF)
   FileWrite($file2,"OfflineAddressBookPath=PT_STRING8,0x660E" & @CRLF)
   FileWrite($file2,"OfflineFolderPathAndFilename=PT_STRING8,0x6610" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Exchange Global Section]" & @CRLF)
   FileWrite($file2,"SectionGUID=13dbb0c8aa05101a9bb000aa002fc45a" & @CRLF)
   FileWrite($file2,"MailboxName=PT_STRING8,0x6607" & @CRLF)
   FileWrite($file2,"HomeServer=PT_STRING8,0x6608" & @CRLF)
   FileWrite($file2,"ConfigFlags=PT_LONG,0x6601" & @CRLF)
   FileWrite($file2,"RPCoverHTTPflags=PT_LONG,0x6623" & @CRLF)
   FileWrite($file2,"RPCProxyServer=PT_UNICODE,0x6622" & @CRLF)
   FileWrite($file2,"RPCProxyPrincipalName=PT_UNICODE,0x6625" & @CRLF)
   FileWrite($file2,"RPCProxyAuthScheme=PT_LONG,0x6627" & @CRLF)
   FileWrite($file2,"AccountName=PT_UNICODE,0x6620" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Microsoft Mail]" & @CRLF)
   FileWrite($file2,"ServiceName=MSFS" & @CRLF)
   FileWrite($file2,"ServerPath=PT_STRING8,0x6600" & @CRLF)
   FileWrite($file2,"Mailbox=PT_STRING8,0x6601" & @CRLF)
   FileWrite($file2,"Password=PT_STRING8,0x67f0" & @CRLF)
   FileWrite($file2,"RememberPassword=PT_BOOLEAN,0x6606" & @CRLF)
   FileWrite($file2,"ConnectionType=PT_LONG,0x6603" & @CRLF)
   FileWrite($file2,"UseSessionLog=PT_BOOLEAN,0x6604" & @CRLF)
   FileWrite($file2,"SessionLogPath=PT_STRING8,0x6605" & @CRLF)
   FileWrite($file2,"EnableUpload=PT_BOOLEAN,0x6620" & @CRLF)
   FileWrite($file2,"EnableDownload=PT_BOOLEAN,0x6621" & @CRLF)
   FileWrite($file2,"UploadMask=PT_LONG,0x6622" & @CRLF)
   FileWrite($file2,"NetBiosNotification=PT_BOOLEAN,0x6623" & @CRLF)
   FileWrite($file2,"NewMailPollInterval=PT_STRING8,0x6624" & @CRLF)
   FileWrite($file2,"DisplayGalOnly=PT_BOOLEAN,0x6625" & @CRLF)
   FileWrite($file2,"UseHeadersOnLAN=PT_BOOLEAN,0x6630" & @CRLF)
   FileWrite($file2,"UseLocalAdressBookOnLAN=PT_BOOLEAN,0x6631" & @CRLF)
   FileWrite($file2,"UseExternalToHelpDeliverOnLAN=PT_BOOLEAN,0x6632" & @CRLF)
   FileWrite($file2,"UseHeadersOnRAS=PT_BOOLEAN,0x6640" & @CRLF)
   FileWrite($file2,"UseLocalAdressBookOnRAS=PT_BOOLEAN,0x6641" & @CRLF)
   FileWrite($file2,"UseExternalToHelpDeliverOnRAS=PT_BOOLEAN,0x6639" & @CRLF)
   FileWrite($file2,"ConnectOnStartup=PT_BOOLEAN,0x6642" & @CRLF)
   FileWrite($file2,"DisconnectAfterRetrieveHeaders=PT_BOOLEAN,0x6643" & @CRLF)
   FileWrite($file2,"DisconnectAfterRetrieveMail=PT_BOOLEAN,0x6644" & @CRLF)
   FileWrite($file2,"DisconnectOnExit=PT_BOOLEAN,0x6645" & @CRLF)
   FileWrite($file2,"DefaultDialupConnectionName=PT_STRING8,0x6646" & @CRLF)
   FileWrite($file2,"DialupRetryCount=PT_STRING8,0x6648" & @CRLF)
   FileWrite($file2,"DialupRetryDelay=PT_STRING8,0x6649" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Personal Folders]" & @CRLF)
   FileWrite($file2,"ServiceName=MSPST MS" & @CRLF)
   FileWrite($file2,"Name=PT_STRING8,0x3001" & @CRLF)
   FileWrite($file2,"PathAndFilenameToPersonalFolders=PT_STRING8,0x6700 " & @CRLF)
   FileWrite($file2,"RememberPassword=PT_BOOLEAN,0x6701" & @CRLF)
   FileWrite($file2,"EncryptionType=PT_LONG,0x6702" & @CRLF)
   FileWrite($file2,"Password=PT_STRING8,0x6703" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Unicode Personal Folders]" & @CRLF)
   FileWrite($file2,"ServiceName=MSUPST MS" & @CRLF)
   FileWrite($file2,"Name=PT_UNICODE,0x3001" & @CRLF)
   FileWrite($file2,"PathAndFilenameToPersonalFolders=PT_STRING8,0x6700 " & @CRLF)
   FileWrite($file2,"RememberPassword=PT_BOOLEAN,0x6701" & @CRLF)
   FileWrite($file2,"EncryptionType=PT_LONG,0x6702" & @CRLF)
   FileWrite($file2,"Password=PT_STRING8,0x6703" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Outlook Address Book]" & @CRLF)
   FileWrite($file2,"ServiceName=CONTAB" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[LDAP Directory]" & @CRLF)
   FileWrite($file2,"ServiceName=EMABLT" & @CRLF)
   FileWrite($file2,"ServerName=PT_STRING8,0x6600" & @CRLF)
   FileWrite($file2,"UserName=PT_STRING8,0x6602" & @CRLF)
   FileWrite($file2,"UseSSL=PT_BOOLEAN,0x6613" & @CRLF)
   FileWrite($file2,"UseSPA=PT_BOOLEAN,0x6615" & @CRLF)
   FileWrite($file2,"EnableBrowsing=PT_BOOLEAN,0x6622" & @CRLF)
   FileWrite($file2,"DisplayName=PT_STRING8,0x3001" & @CRLF)
   FileWrite($file2,"ConnectionPort=PT_STRING8,0x6601" & @CRLF)
   FileWrite($file2,"SearchTimeout=PT_STRING8,0x6607" & @CRLF)
   FileWrite($file2,"MaxEntriesReturned=PT_STRING8,0x6608" & @CRLF)
   FileWrite($file2,"SearchBase=PT_STRING8,0x6603" & @CRLF)
   FileWrite($file2,"CheckNames=PT_STRING8,0x6624" & @CRLF)
   FileWrite($file2,"DefaultSearch=PT_LONG,0x6623" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Microsoft Outlook Client]" & @CRLF)
   FileWrite($file2,"SectionGUID=0a0d020000000000c000000000000046" & @CRLF)
   FileWrite($file2,"FormDirectoryPage=PT_STRING8,0x0270" & @CRLF)
   FileWrite($file2,"WebServicesLocation=PT_STRING8,0x0271" & @CRLF)
   FileWrite($file2,"ComposeWithWebServices=PT_BOOLEAN,0x0272" & @CRLF)
   FileWrite($file2,"PromptWhenUsingWebServices=PT_BOOLEAN,0x0273" & @CRLF)
   FileWrite($file2,"OpenWithWebServices=PT_BOOLEAN,0x0274" & @CRLF)
   FileWrite($file2,"CachedExchangeMode=PT_LONG,0x041f" & @CRLF)
   FileWrite($file2,"CachedExchangeSlowDetect=PT_BOOLEAN,0x0420" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[Personal Address Book]" & @CRLF)
   FileWrite($file2,"ServiceName=MSPST AB" & @CRLF)
   FileWrite($file2,"NameOfPAB=PT_STRING8,0x001e3001" & @CRLF)
   FileWrite($file2,"PathAndFilename=PT_STRING8,0x001e6600" & @CRLF)
   FileWrite($file2,"ShowNamesBy=PT_LONG,0x00036601" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"; ************************************************************************" & @CRLF)
   FileWrite($file2,"; Section 7 - Mapping for internet account properties.  DO NOT MODIFY." & @CRLF)
   FileWrite($file2,"; ************************************************************************" & @CRLF)
   FileWrite($file2 , @CRLF)
   FileWrite($file2,"[I_Mail]" & @CRLF)
   FileWrite($file2,"AccountType=POP3" & @CRLF)
   FileWrite($file2,";--- POP3 Account Settings ---" & @CRLF)
   FileWrite($file2,"AccountName=PT_UNICODE,0x0002" & @CRLF)
   FileWrite($file2,"DisplayName=PT_UNICODE,0x000B" & @CRLF)
   FileWrite($file2,"EmailAddress=PT_UNICODE,0x000C" & @CRLF)
   FileWrite($file2,";--- POP3 Account Settings ---" & @CRLF)
   FileWrite($file2,"POP3Server=PT_UNICODE,0x0100" & @CRLF)
   FileWrite($file2,"POP3UserName=PT_UNICODE,0x0101" & @CRLF)
   FileWrite($file2,"POP3UseSPA=PT_LONG,0x0108" & @CRLF)
   FileWrite($file2,"Organization=PT_UNICODE,0x0107" & @CRLF)
   FileWrite($file2,"ReplyEmailAddress=PT_UNICODE,0x0103" & @CRLF)
   FileWrite($file2,"POP3Port=PT_LONG,0x0104" & @CRLF)
   FileWrite($file2,"POP3UseSSL=PT_LONG,0x0105" & @CRLF)
   FileWrite($file2,"; --- SMTP Account Settings ---" & @CRLF)
   FileWrite($file2,"SMTPServer=PT_UNICODE,0x0200" & @CRLF)
   FileWrite($file2,"SMTPUseAuth=PT_LONG,0x0203" & @CRLF)
   FileWrite($file2,"SMTPAuthMethod=PT_LONG,0x0208" & @CRLF)
   FileWrite($file2,"MTPUserName=PT_UNICODE,0x0204" & @CRLF)
   FileWrite($file2,"SMTPUseSPA=PT_LONG,0x0207" & @CRLF)
   FileWrite($file2,"ConnectionType=PT_LONG,0x000F" & @CRLF)
   FileWrite($file2,"ConnectionOID=PT_UNICODE,0x0010" & @CRLF)
   FileWrite($file2,"SMTPPort=PT_LONG,0x0201" & @CRLF)
   FileWrite($file2,"SMTPSecureConnection=PT_LONG,0x020A" & @CRLF)
   FileWrite($file2,"ServerTimeOut=PT_LONG,0x0209" & @CRLF)
   FileWrite($file2,"LeaveOnServer=PT_LONG,0x1000" & @CRLF)
   FileWrite($file2,"" & @CRLF)
   FileWrite($file2,"[IMAP_I_Mail]" & @CRLF)
   FileWrite($file2,"AccountType=IMAP" & @CRLF)
   FileWrite($file2,";--- IMAP Account Settings ---" & @CRLF)
   FileWrite($file2,"AccountName=PT_UNICODE,0x0002" & @CRLF)
   FileWrite($file2,"DisplayName=PT_UNICODE,0x000B" & @CRLF)
   FileWrite($file2,"EmailAddress=PT_UNICODE,0x000C" & @CRLF)
   FileWrite($file2,";--- IMAP Account Settings ---" & @CRLF)
   FileWrite($file2,"IMAPServer=PT_UNICODE,0x0100" & @CRLF)
   FileWrite($file2,"IMAPUserName=PT_UNICODE,0x0101" & @CRLF)
   FileWrite($file2,"IMAPUseSPA=PT_LONG,0x0108" & @CRLF)
   FileWrite($file2,"Organization=PT_UNICODE,0x0107" & @CRLF)
   FileWrite($file2,"ReplyEmailAddress=PT_UNICODE,0x0103" & @CRLF)
   FileWrite($file2,"IMAPPort=PT_LONG,0x0104" & @CRLF)
   FileWrite($file2,"IMAPUseSSL=PT_LONG,0x0105" & @CRLF)
   FileWrite($file2,"; --- SMTP Account Settings ---" & @CRLF)
   FileWrite($file2,"SMTPServer=PT_UNICODE,0x0200" & @CRLF)
   FileWrite($file2,"SMTPUseAuth=PT_LONG,0x0203" & @CRLF)
   FileWrite($file2,"SMTPAuthMethod=PT_LONG,0x0208" & @CRLF)
   FileWrite($file2,"SMTPUserName=PT_UNICODE,0x0204" & @CRLF)
   FileWrite($file2,"SMTPUseSPA=PT_LONG,0x0207" & @CRLF)
   FileWrite($file2,"ConnectionType=PT_LONG,0x000F" & @CRLF)
   FileWrite($file2,"ConnectionOID=PT_UNICODE,0x0010" & @CRLF)
   FileWrite($file2,"SMTPPort=PT_LONG,0x0201" & @CRLF)
   FileWrite($file2,"SMTPSecureConnection=PT_LONG,0x020A" & @CRLF)
   FileWrite($file2,"ServerTimeOut=PT_LONG,0x0209" & @CRLF)
   FileWrite($file2,"CheckNewImap=PT_LONG,0x1100" & @CRLF)
   FileWrite($file2,"RootFolder=PT_UNICODE,0x1101" & @CRLF)
   FileWrite($file2,"Account=PT_UNICODE,0x0002" & @CRLF)
   FileWrite($file2,"HttpServer=PT_UNICODE,0x0100" & @CRLF)
   FileWrite($file2,"UserName=PT_UNICODE,0x0101" & @CRLF)
   FileWrite($file2,"Organization=PT_UNICODE,0x0107" & @CRLF)
   FileWrite($file2,"UseSPA=PT_LONG,0x0108" & @CRLF)
   FileWrite($file2,"TimeOut=PT_LONG,0x0209" & @CRLF)
   FileWrite($file2,"Reply=PT_UNICODE,0x0103" & @CRLF)
   FileWrite($file2,"EmailAddress=PT_UNICODE,0x000C" & @CRLF)
   FileWrite($file2,"FullName=PT_UNICODE,0x000B" & @CRLF)
   FileWrite($file2,"Connection Type=PT_LONG,0x000F" & @CRLF)
   FileWrite($file2,"ConnectOID=PT_UNICODE,0x0010" & @CRLF)
   FileClose($file2)
EndFunc